version: 2
jobs:

  install:
    macos:
      xcode: '9.2.0'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Installing Dependencies
          command: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    macos:
      xcode: '9.2.0'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Building Renderer
          command: yarn build-renderer
      - run:
          name: Bundling Application
          command: yarn build-app --publish 'never'
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - renderer/.next
            - renderer/out

  test-lint:
    macos:
      xcode: '9.2.0'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting Code
          command: yarn test-lint

  deploy:
    macos:
      xcode: '9.2.0'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploying to GitHub
          command: yarn build-app

workflows:
  version: 2
  unscheduled:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test-lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
